name: Preternatural Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-14
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Run Preternatural Build (Xcode 16)
      uses: PreternaturalAI/github-action/preternatural-build@main
      with:
        xcode-version: '16'
        build_all_platforms: 'true'
        architectures: 'arm64'
        configuration: 'debug'
