name: Preternatural Build
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: macos-14
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Run Preternatural Build (Xcode 16)
      uses: PreternaturalAI/github-action/preternatural-build@main
      with:
        xcode-version: '16'
        configuration: 'debug'
